---

- name: add mongodb key
  apt_key: id=EA312927 keyserver=hkp://keyserver.ubuntu.com state=present
  when: ansible_os_family == "Debian"

- name: add mongodb repository
  apt_repository: "repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main' state=present update_cache=yes"
  when: ansible_os_family == "Debian"

- name: install mongodb
  apt: "pkg=mongodb-org state={{ mongodb_state }}"
  when: ansible_os_family == "Debian"

- name: write mongodb.yml
  template: src=mongod.conf.j2 dest=/etc/mongod.conf owner=root group=root mode=0644
  notify:
    - restart mongod

- name: enable mongod service
  service: name=mongod enabled=yes state=started
